### ISSUE TITLE
Problems parsing BYMONTH 

### ISSUE THREAD

**Issue by myzinsky** [johngrogg/ics-parser#27] opened 2015-06-03 13:25 UTC
Notice: Undefined index: BYMONTH in /var/www/calendar/ics-parser/class.iCalReader.php on line 490

**Comment by u01jmg3** [comment] 2015-06-03 13:45
Do you have an example iCal snippet for me to test against? Are you using the latest [dev-master](https://github.com/johngrogg/ics-parser/archive/master.zip) branch?

**Comment by u01jmg3** [comment] 2015-06-07 19:37
Closing as duplicate of #28

**Closed by u01jmg3** 2015-06-07 19:37 UTC
Labels: awaiting-feedback
